# permissions for end users to view pluginsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pluginsubscription-viewer-role
rules:
- apiGroups:
  - kubeeyeplugins.kubesphere.io
  resources:
  - pluginsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeeyeplugins.kubesphere.io
  resources:
  - pluginsubscriptions/status
  verbs:
  - get
