apiVersion: v1
kind: Pod
metadata:
  name: ntp
  namespace: default
spec:
  containers:
    - command: ["sh"]
      args: ["-c", "echo 'kubectl cp default/ntp:/root/check_ntp.sh /tmp/check_ntp.sh && chmod +x /tmp/check_ntp.sh && sh /tmp/check_ntp.sh' | nsenter -t 1 -m -u -i -n;sleep 600"]
      image: {{.NtpImage}}
      name: ntp
      securityContext:
        privileged: true
  hostIPC: true
  hostNetwork: true
  hostPID: true
