apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ template "charts.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      {{- toYaml .Values.spec | nindent 6 }}