apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    {{- toYaml .Values.managerConfig | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
