apiVersion: v1
kind: Service
metadata:
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ include "charts.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
    - name: https
      port: {{ .Values.service.metricsPort }}
      protocol: TCP
      targetPort: https
  selector:
    {{- toYaml .Values.labels | nindent 4 }}

